# Simulation settings
simulation:
  persona_files:
    - "/Users/dietmar/Dropbox/PycharmProjects/persona2interviews/data/inputs/persona//US_News_100_Jobs.csv"
  moderator_criteria:
    role: "moderator"
  participant_criteria:
    role: "participant"
  iterations: 1
#  last_words_used: 1000  # Number of last words to use for token analysis
  last_words_used: -1  # Use _all_ words, no limit






# Interview/Focus Group settings
one_to_one_interview:
  enabled: true
focus_group:
  enabled: false

# Output settings
output:
#  directory: "data/outputs/results/interviews/"
  directory: "data/outputs/results/4analysis/"
  diversity_files:
    - "data/outputs/questionnaire/persona_pool1-5.csv"    
#    - "data/outputs/questionnaire/diversity00.csv"
#    - "data/outputs/questionnaire/diversity01.csv"
#   - "data/outputs/questionnaire/diversity02.csv"
#   - "data/outputs/questionnaire/diversity03.csv"
#   - "data/outputs/questionnaire/diversity04.csv"
#   - "data/outputs/questionnaire/diversity05.csv"
#   - "data/outputs/questionnaire/diversity06.csv"

# Token Tracking settings
token_tracking:
  enabled: true
  output_directory: "data/outputs/token_tracking/"
  output_file: "token_distribution_persona_pool1-5.csv"


# AI settings
advanced:
  model: "gpt-3.5-turbo"
  model: "gpt-4.0"
  max_tokens: 150
  temperature: 0.7
  max_turns: 5

# OpenAI API settings
openai:
  api_key: ${OPENAI_API_KEY}

# Logging settings
logging:
  file: "data/logs/simulation.log"
  level: "INFO"

# System prompts
system_prompts:
  moderator: "data/inputs/prompts/moderator_prompt.txt"
  participant: "data/inputs/prompts/participant_prompt.txt"



# Topic file
topic_file: "data/inputs/topics/topics4discussion.csv"
